// metronic-tailwind-angular/src/app/app.component.ts
import { AfterViewInit, Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './header/header.component';
import { FooterComponent } from './footer/footer.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import KTComponents from '../metronic/core/index';
import KTLayout from '../metronic/app/layouts/demo1';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [RouterOutlet, HeaderComponent, FooterComponent, SidebarComponent],
	templateUrl: './app.component.html',
	styleUrl: './app.component.scss'
})
export class AppComponent implements AfterViewInit, OnInit {
	title = 'metronic-tailwind-angular';

	ngAfterViewInit(): void {
		KTComponents.init();
		KTLayout.init();
	}

	ngOnInit(): void {
	}
}


<div class="flex grow">
	<app-sidebar></app-sidebar>
	<div class="wrapper flex grow flex-col">
		<app-header></app-header>
		<main class="grow content pt-5" id="content" role="content">
			<!-- begin: container -->
			<div class="container-fixed" id="content_container">
			</div>
			<!-- end: container -->
			<!-- begin: container -->
			<div class="container-fixed">
				<router-outlet></router-outlet>
			</div>
			<!-- end: container -->
		</main>
		<app-footer></app-footer>
	</div>
</div>

// metronic-react-tailwind/src/App.tsx
import './App.css';
import Sidebar from './Sidebar';
import Footer from './Footer';
import Header from './Header';
import KTComponent from './theme/core/index.spa';
import { useEffect } from 'react';
import KTLayout from './theme/app/layouts/demo1.js';


function App() {  
  useEffect(() => {
    KTComponent.init();
    KTLayout.init();
  }, []);

  return (
    <>
      <div className="flex grow">
        <Sidebar />
        <div className="wrapper flex grow flex-col">
          <Header />
          <main className="grow content pt-5" id="content" role="content">
          <div className="container-fixed" id="content_container">
          </div>
          <div className="container-fixed">
            {/* put your content here */}
          </div>
          </main>
          <Footer />
        </div>
      </div>
    </>
  )
}

export default App
